### ISSUE TITLE
[홈] 오늘이 마지막 세션인 경우 버그

### ISSUE THREAD

**Issue by sanghee-dev** [YAPP-admin/attendance-ios#159]
## 할 일
오늘이 마지막 세션인 경우
- [x] 모든 세션을 끝마쳤습니다가 뜨는 버그
- [ ] 100점으로 표시됨

**Comment by BOMS2** [comment]
updateWhenAllSessionsCompleted 함수가 모든 세션을 끝마쳤습니다로 잘 뜨는 중
