### ISSUE TITLE
[홈] 점수가 실시간으로 업데이트되지 않는 문제

### ISSUE THREAD

**Issue by sanghee-dev** [YAPP-admin/attendance-ios#160]
## 할 일
- [ ] 점수가 실시간으로 업데이트되지 않는 문제 해결

## 참고
- 출결을 한 이후 점수가 화면이 업데이트되어야 함
- 파이어베이스에서 점수 변경시 실시간으로 화면이 업데이트되어야 함

**Comment by BOMS2** [comment]
아래 탭하면 업데이트 되도록 수정
