### ISSUE TITLE
[Home] 오늘 세션 정보가 잘못 표기됨

### ISSUE THREAD

**Issue by sanghee-dev** [YAPP-admin/attendance-ios#176]
## 상세
- 현재 세션 정보가 잘못 표기됨
- 테스트 기준 6월 19일이므로 6월 20일 세션이 표시되어야 하는데, 6월 19일 세션이 표시됨
- *qr 클릭시 지금은 로그인할 수 없다고 뜨는데, 오늘 세션이 잘못 떠서 발생한 문제겠죠 ??

## 화면
| 화면 1 | 화면 2 |
| :-: | :-: |
| <img width="200" src="https://user-images.githubusercontent.com/61302874/174478715-8726e3ff-6de3-4920-b414-a1e0d99e3f3a.PNG" > | <img width="200" src="https://user-images.githubusercontent.com/61302874/174478717-ec8243b7-fab0-4e41-89a3-5a01d42b1e74.PNG" > |

**Comment by BOMS2** [comment]
현재 날짜와 시간을 기준으로 기준 세션을 잡기 때문에 같은 날 세션이 없는게 맞을 것 같음
